name: abstarct_date
description: Abstract date is a fluent abstract date system for working with different date types.
version: 1.0.0
homepage: https://github.com/ali2236/abstarct_date
author: Aligator <aligator2236@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shamsi_date: ^0.15.0

dev_dependencies:
  test: ^1.16.0
